# Generated by Django 3.2.25 on 2026-03-05 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('airline', models.CharField(max_length=100, verbose_name='Авиакомпания')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Город вылета')),
                ('arrival_city', models.CharField(max_length=100, verbose_name='Город прилёта')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прилёта')),
                ('flight_type', models.CharField(choices=[('arrival', 'Прилёт'), ('departure', 'Вылет')], max_length=10, verbose_name='Тип рейса')),
                ('gate', models.CharField(max_length=10, verbose_name='Гейт')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField(verbose_name='Дата рейса')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flights_api.flight', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=10, verbose_name='Место')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('ticket_number', models.CharField(blank=True, max_length=50, verbose_name='Номер билета')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights_api.flight', verbose_name='Рейс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'unique_together': {('flight', 'user', 'seat')},
            },
        ),
    ]
